### ISSUE TITLE
关于新能源车牌识别问题

### ISSUE THREAD

**Issue by Vivianwxf** [huxiaoman7/mxnet-cnn-plate-recognition#1]
请问作者，关于新能源绿色车牌的识别，训练代码要如何考虑设计？是否能够将7位车牌和8位车牌放在一起训练？

**Comment by huxiaoman7** [comment]
hi，你好，新能源车排的需要单独训练，一是因为位数不一样，二是后面的bgm以及和传统的也不一样，不论是传统的方式分割还是网络训练都需要单独去训练~当然如果你有更好的方法也可以告诉我
