### ISSUE TITLE
车牌生成

### ISSUE THREAD

**Issue by ZERO6666** [huxiaoman7/mxnet-cnn-plate-recognition#11]
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

我用的python3 使用车牌生成报这个错误，是因为opencv对2和3区别所导致的吗？还是哪里的问题呢？请问

**Comment by ZERO6666** [comment]
已经解决 主要一些 python2 3函数的差异

**Comment by chuyhu** [comment]
请问，这个python版本问题，您是怎么解决的呢？python降版本吗？还是其他的方法
